# Generated by Django 5.2 on 2025-05-03 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_verbalmemorytest_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verbalmemorytest",
            options={"ordering": ["-score"]},
        ),
        migrations.RemoveField(
            model_name="verbalmemorytest",
            name="max_level",
        ),
        migrations.CreateModel(
            name="ChimpTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("sequence_length", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "-sequence_length"],
            },
        ),
    ]
